# Generated by Django 5.0 on 2023-12-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbKlasifikasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('klasifikasi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Klasifikasi',
            },
        ),
        migrations.CreateModel(
            name='DbSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('klasifikasi', models.CharField(max_length=30)),
                ('tgl_agenda', models.DateField()),
                ('no_agenda', models.CharField(max_length=30)),
                ('tgl_surat', models.DateField()),
                ('no_surat', models.CharField(max_length=30)),
                ('surat_dari', models.CharField(max_length=110)),
                ('perihal', models.CharField(max_length=200)),
                ('upload_file', models.FileField(upload_to='Surat')),
            ],
            options={
                'db_table': 'DbSurat',
            },
        ),
        migrations.CreateModel(
            name='DisposisiDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_agenda', models.CharField(max_length=30, null=True)),
                ('upload_file_disposisi', models.FileField(upload_to='Disposisi')),
                ('no_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_app.dbsurat')),
            ],
            options={
                'db_table': 'DisposisiDb',
            },
        ),
    ]
