# Generated by Django 5.0 on 2023-12-12 11:13

import surat_tu_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(max_length=30)),
                ('klasifikasi', models.CharField(max_length=30)),
                ('tgl_agenda', models.DateField()),
                ('no_agenda', models.TextField(max_length=200)),
                ('tgl_surat', models.DateField()),
                ('surat_dari', models.CharField(max_length=200)),
                ('perihal', models.CharField(max_length=200)),
                ('upload_file', models.FileField(upload_to=surat_tu_app.models.user_folder)),
            ],
            options={
                'db_table': 'DbSurat',
            },
        ),
    ]
