# Generated by Django 5.0 on 2023-12-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposisidb',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='disposisidb',
            name='disposisi',
        ),
        migrations.RemoveField(
            model_name='disposisidb',
            name='tgl_agenda',
        ),
    ]
