# Generated by Django 5.0 on 2023-12-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('klasifikasi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Klasifikasi',
            },
        ),
    ]
