# Generated by Django 5.0 on 2023-12-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposisidb',
            old_name='no_surat',
            new_name='disposisi',
        ),
    ]
