# Generated by Django 5.0 on 2023-12-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='dbsurat',
            name='no_surat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_app.nosurat'),
        ),
        migrations.AlterField(
            model_name='disposisidb',
            name='no_surat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_app.nosurat'),
        ),
    ]
