# Generated by Django 5.0 on 2023-12-17 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0002_rename_no_surat_disposisidb_disposisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposisidb',
            name='DbSurat',
        ),
        migrations.AddField(
            model_name='disposisidb',
            name='no_surat',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
