# Generated by Django 5.0 on 2023-12-23 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0002_nosurat_alter_dbsurat_no_surat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisidb',
            name='no_surat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_app.dbsurat'),
        ),
        migrations.AlterField(
            model_name='dbsurat',
            name='no_surat',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='disposisidb',
            name='disposisi',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NoSurat',
        ),
    ]
