# Generated by Django 5.0 on 2023-12-20 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0002_remove_disposisidb_catatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisidb',
            name='disposisi',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
