# Generated by Django 5.0 on 2023-12-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0003_remove_disposisidb_dbsurat_disposisidb_no_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisidb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
