# Generated by Django 5.0 on 2023-12-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0003_dbsurat_no_surat_alter_dbsurat_no_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbsurat',
            name='no_agenda',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dbsurat',
            name='no_surat',
            field=models.CharField(max_length=30),
        ),
    ]
