# Generated by Django 5.0 on 2023-12-13 07:57

import django.db.models.deletion
import surat_tu_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0005_dbsurat_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposisiBagum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(max_length=200, null=True)),
                ('upload_file_disposisi_bagum', models.FileField(null=True, upload_to=surat_tu_app.models.disposisi_bagum)),
                ('no_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_app.dbsurat')),
            ],
            options={
                'db_table': 'DisposisiBagum',
            },
        ),
        migrations.CreateModel(
            name='DisposisiKabadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(max_length=200, null=True)),
                ('upload_file_disposisi_kabadan', models.FileField(null=True, upload_to=surat_tu_app.models.disposisi_kabadan)),
                ('no_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_app.dbsurat')),
            ],
            options={
                'db_table': 'DisposisiKabadan',
            },
        ),
        migrations.CreateModel(
            name='DisposisiSes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(max_length=200, null=True)),
                ('upload_file_disposisi_ses', models.FileField(null=True, upload_to=surat_tu_app.models.disposisi_ses)),
                ('no_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_app.dbsurat')),
            ],
            options={
                'db_table': 'DisposisiSes',
            },
        ),
    ]
