# Generated by Django 5.0 on 2023-12-15 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_app', '0006_disposisibagum_disposisikabadan_disposisises'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisibagum',
            name='no_agenda',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='disposisibagum',
            name='tgl_agenda',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disposisikabadan',
            name='no_agenda',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='disposisikabadan',
            name='tgl_agenda',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disposisises',
            name='no_agenda',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='disposisises',
            name='tgl_agenda',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
