# Generated by Django 5.0 on 2024-01-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('tanggal', models.DateField(null=True)),
            ],
            options={
                'db_table': 'NotaDinas',
            },
        ),
    ]
