# Generated by Django 5.0 on 2024-01-21 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_keluar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notadinas',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SemuaNotaDinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('tanggal', models.DateField()),
                ('no_takah', models.CharField(max_length=30)),
                ('kepada', models.CharField(max_length=30)),
                ('perihal', models.CharField(max_length=200)),
                ('keterangan', models.CharField(max_length=200)),
                ('keterangan_tambahan', models.CharField(max_length=200)),
                ('id_nota_dinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surat_tu_keluar.notadinas')),
            ],
            options={
                'db_table': 'SemuaNotaDinas',
            },
        ),
    ]
