# Generated by Django 5.0 on 2024-01-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_keluar', '0002_alter_notadinas_tanggal_semuanotadinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semuanotadinas',
            name='keterangan_tambahan',
        ),
        migrations.RemoveField(
            model_name='semuanotadinas',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='semuanotadinas',
            name='bagian',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='semuanotadinas',
            name='catatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='semuanotadinas',
            name='no_urut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='semuanotadinas',
            name='kepada',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='semuanotadinas',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='semuanotadinas',
            name='no_takah',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='semuanotadinas',
            name='perihal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
