# Generated by Django 5.0 on 2024-01-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_keluar', '0002_rename_catatan_notadinas_bon_oleh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notadinas',
            old_name='bon_oleh',
            new_name='catatan',
        ),
    ]
