# Generated by Django 5.0 on 2024-01-24 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_keluar', '0003_remove_semuanotadinas_keterangan_tambahan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semuanotadinas',
            name='no_urut',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
