# Generated by Django 5.0 on 2024-02-28 08:23

import django.core.validators
import surat_tu_keluar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_keluar', '0003_rename_bon_oleh_notadinas_catatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biasa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('tanggal', models.DateField()),
                ('no_urut', models.CharField(max_length=50)),
                ('no_takah', models.CharField(blank=True, max_length=30, null=True)),
                ('kepada', models.CharField(blank=True, max_length=30, null=True)),
                ('perihal', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('bagian', models.CharField(blank=True, max_length=10, null=True)),
                ('catatan', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=surat_tu_keluar.models.save_file_biasa, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'db_table': 'Biasa',
            },
        ),
    ]
