# Generated by Django 5.0 on 2024-01-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_keluar', '0004_alter_semuanotadinas_no_urut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semuanotadinas',
            old_name='id_nota_dinas',
            new_name='id_semua_nota_dinas',
        ),
    ]
