# Generated by Django 5.0 on 2024-03-27 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tu_keluar', '0005_notadinas_no_urut_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasa',
            name='no_urut_temp',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
